### PR TITLE
Make EBA build with a modern OCaml ecosystem

### PR DESCRIPTION
**Pull request by andersfischernielsen**
`jbuilder` is deprecated and `dune` should be used instead. 
This PR updates the build configuration to reflect that while also updating the `Dolog` module.

### CODE REVIEW

**Comment by IagoAbal** [comment]
Thanks @andersfischernielsen. Are you familiar with `git rebase`? I like the changes but I would prefer if some of them were squashed. I do appreciate a lot that we keep the Git history a bit clean, although no need to exaggerate of course.

Basically, all commits except 7c4bc28c1b705ee2f7bcb3f7c2d857b613b1adbb could be squashed into a single commit. Ideally this change `"dolog" {>= "4.0.0"}` should go out of this PR. Or you can squash everything together with PR #4  into a single commit titled "Make EBA build with a modern OCaml ecosystem" or something. Some of the commits are undoing stuff done by previous commits and that will make the history a bit messy.

Regarding commit 7c4bc28c1b705ee2f7bcb3f7c2d857b613b1adbb, it would be nicer if you create `.gitignore` but leave `.hgignore`. I was actually using Hg and I just pushed to GitHub using the hg-git bridge. I must drop Hg here, but haven't done it yet. When I do it I'll remove `.hgignore`.

Thanks!

**Comment by andersfischernielsen** [comment]
I'll try to sqeeze everything together. Thanks! 👍

**Comment by andersfischernielsen** [comment]
@IagoAbal When you have the time, can you review this (again)? 👍

**Comment by IagoAbal** [comment]
Thanks for rebasing!

**Pull request merged**
